Support Twitter oauth login
kreait/firebase-php pull request #481
Opened 2020-10-12 03:40 UTC by chyt

According to [Firebase docs](https://cloud.google.com/identity-platform/docs/reference/rest/v1/accounts/signInWithIdp), OAuth token secret is required to support logging in with Twitter using an OAuth 1.0 credential:

> If the user is signing in to the Twitter provider using a Twitter OAuth 1.0 credential, this should be set to accessToken=[TWITTER_ACCESS_TOKEN]&oauthTokenSecret=[TWITTER_TOKEN_SECRET]&providerId=twitter.com, where [TWITTER_ACCESS_TOKEN] and [TWITTER_TOKEN_SECRET] should be replaced with the Twitter OAuth access token and Twitter OAuth token secret respectively.

This PR adds the ability to specify such a secret when signing in using an IDP access token. Unfortunately there are no tests, but hopefully this will provide the basic implementation for this capability.

2020-10-12 09:01 UTC, jeromegamez requested changes

2020-10-12 09:01 UTC, jeromegamez commented on src/Firebase/Auth/SignInWithIdpCredentials.php
> +        $instance->accessToken = $accessToken;
```suggestion
        $instance = self::withAccessToken($provider, $accessToken);
```

2020-10-14 22:50 UTC, chyt commented on src/Firebase/Auth.php
> +    public function signInWithIdpAccessToken($provider, string $accessToken, string $oauthTokenSecret = null, $redirectUrl = null): SignInResult
Fixed

2020-10-14 22:50 UTC, chyt commented on src/Firebase/Auth/SignInWithIdpCredentials.php
> +        $instance->accessToken = $accessToken;
Fixed

2020-10-14 22:51 UTC, chyt commented on src/Firebase/Auth.php
> +            ->withClearTextPassword($password));
Running that command changes a bunch of additional files. I ended up manually reverting the linespace changes.

2020-10-17 00:00 UTC, jeromegamez commented
Good work!  🙌  I merged your changes with 37f5ae9d78b00d78d2eb32b4a4f641d118a6bf86 (I just made the last CS change and added a test, while making sure that you're associated with the commit) and [added some more convenience methods](https://github.com/kreait/firebase-php/commit/d7d40edf6068069f4464607fa2bbf7b7b5624c88) while I was at it 😅 

Thank you! 🌺

2020-10-17 00:00 UTC, closed without merging